#!/bin/bash

cd ~
wget https://github.com/ervandew/eclim/releases/download/2.8.0/eclim_2.8.0.bin
./eclim_2.8.0.bin
sudo chmod +rwx eclim_2.8.0.bin
./eclim_2.8.0.bin \
     --yes \
     --eclipse /opt/eclipse \
     --vimfiles "$HOME/.vim" \
     --plugins=jdt,pydev,vimplugin,dltk,dltkruby
