#!/bin/bash

brightness_file="/sys/class/leds/tpacpi::kbd_backlight/brightness"
sudo chmod 666 "$brightness_file"

brightness_value=$(cat "$brightness_file")

# if greater than or equal to 2, set it to 0
if [[ $brightness_value == 2 ]]; then
  echo 0 > "$brightness_file"

# if at 1, set it to 2
elif [[ $brightness_value == 1 ]]; then
  echo 2 > "$brightness_file"

# if 0 or less than 0, set it to 1
elif [[ $brightness_value == 0 ]]; then
  echo 1 > "$brightness_file"
fi
